"""Detection signals for Provenance Guard.

Signal 1 (this file, M3): Groq LLM classification. Asks a model to judge how
AI-generated a piece of text reads and return a probability. This captures
semantic/stylistic coherence holistically.

Signal 2 (stylometric heuristics) and the combine/interpret logic are added
in M4.
"""

import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

GROQ_MODEL = "llama-3.3-70b-versatile"

# System prompt asks for a strict JSON object so we can parse a numeric score.
_SYSTEM_PROMPT = (
    "You are an AI-text detector. Given a piece of text, estimate the "
    "probability that it was generated by an AI language model rather than "
    "written by a human. Respond ONLY with a JSON object of the form "
    '{"p_ai": <number between 0 and 1>, "reasoning": "<one short sentence>"}. '
    "A value near 1 means almost certainly AI-generated; a value near 0 means "
    "almost certainly human-written; 0.5 means genuinely unsure."
)

_client = None


def _get_client():
    """Lazily create the Groq client so importing this module never fails."""
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


def groq_signal(text):
    """Return the Groq signal for `text`.

    Returns a dict: {"p_ai": float in [0, 1], "reasoning": str}.
    Raises on API/parse failure so the caller can decide how to handle it.
    """
    response = _get_client().chat.completions.create(
        model=GROQ_MODEL,
        temperature=0.0,  # low temp -> more consistent, repeatable scores
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )
    raw = response.choices[0].message.content
    data = json.loads(raw)

    p_ai = float(data.get("p_ai"))
    p_ai = max(0.0, min(1.0, p_ai))  # clamp defensively into [0, 1]
    reasoning = str(data.get("reasoning", "")).strip()

    return {"p_ai": p_ai, "reasoning": reasoning}


if __name__ == "__main__":
    # Quick standalone test: `python detection.py`
    samples = {
        "clearly AI": (
            "Artificial intelligence represents a transformative paradigm shift "
            "in modern society. It is important to note that while the benefits "
            "of AI are numerous, it is equally essential to consider the ethical "
            "implications."
        ),
        "clearly human": (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but way too much sodium and i was "
            "thirsty for like three hours after."
        ),
    }
    for label, sample in samples.items():
        result = groq_signal(sample)
        print(f"[{label}] p_ai={result['p_ai']:.2f} :: {result['reasoning']}")
